import { Pokemon } from '../parser/types';
import { getNationalDexId } from './speciesMapping';

export const NATURES: string[] = [
    'Hardy', 'Lonely', 'Brave', 'Adamant', 'Naughty',
    'Bold', 'Docile', 'Relaxed', 'Impish', 'Lax',
    'Timid', 'Hasty', 'Serious', 'Jolly', 'Naive',
    'Modest', 'Mild', 'Quiet', 'Bashful', 'Rash',
    'Calm', 'Gentle', 'Sassy', 'Careful', 'Quirky'
];

export function getNature(pid: number): string {
    const index = Math.abs(pid) % 25;
    return NATURES[index] || 'Hardy';
}

export const POKEBALLS: Record<number, string> = {
    1: 'Master Ball',
    2: 'Ultra Ball',
    3: 'Great Ball',
    4: 'Poké Ball',
    5: 'Safari Ball',
    6: 'Net Ball',
    7: 'Dive Ball',
    8: 'Nest Ball',
    9: 'Repeat Ball',
    10: 'Timer Ball',
    11: 'Luxury Ball',
    12: 'Premier Ball'
};

export function getPokeballName(id: number): string {
    return POKEBALLS[id] || 'Poké Ball';
}

export function isShiny(pokemon: Pokemon): boolean {
    if (!pokemon.pid || !pokemon.otid) return false;
    const p1 = pokemon.pid & 0xffff;
    const p2 = (pokemon.pid >>> 16) & 0xffff;
    const tid = pokemon.otid & 0xffff;
    const sid = (pokemon.otid >>> 16) & 0xffff;
    return ((tid ^ sid ^ p1 ^ p2) >>> 0) < 8;
}

export interface PokemonTypeInfo {
    primary: string;
    secondary?: string;
}

// Gen 1 to Gen 3 core species primary/secondary types
export const SPECIES_TYPES: Record<number, PokemonTypeInfo> = {
    // Starters & Gen 1
    1: { primary: 'GRASS', secondary: 'POISON' },
    2: { primary: 'GRASS', secondary: 'POISON' },
    3: { primary: 'GRASS', secondary: 'POISON' },
    4: { primary: 'FIRE' },
    5: { primary: 'FIRE' },
    6: { primary: 'FIRE', secondary: 'FLYING' },
    7: { primary: 'WATER' },
    8: { primary: 'WATER' },
    9: { primary: 'WATER' },
    10: { primary: 'BUG' },
    11: { primary: 'BUG' },
    12: { primary: 'BUG', secondary: 'FLYING' },
    13: { primary: 'BUG', secondary: 'POISON' },
    14: { primary: 'BUG', secondary: 'POISON' },
    15: { primary: 'BUG', secondary: 'POISON' },
    16: { primary: 'NORMAL', secondary: 'FLYING' },
    17: { primary: 'NORMAL', secondary: 'FLYING' },
    18: { primary: 'NORMAL', secondary: 'FLYING' },
    19: { primary: 'NORMAL' },
    20: { primary: 'NORMAL' },
    21: { primary: 'NORMAL', secondary: 'FLYING' },
    22: { primary: 'NORMAL', secondary: 'FLYING' },
    23: { primary: 'POISON' },
    24: { primary: 'POISON' },
    25: { primary: 'ELECTRIC' },
    26: { primary: 'ELECTRIC' },
    27: { primary: 'GROUND' },
    28: { primary: 'GROUND' },
    29: { primary: 'POISON' },
    30: { primary: 'POISON' },
    31: { primary: 'POISON', secondary: 'GROUND' },
    32: { primary: 'POISON' },
    33: { primary: 'POISON' },
    34: { primary: 'POISON', secondary: 'GROUND' },
    35: { primary: 'NORMAL' },
    36: { primary: 'NORMAL' },
    37: { primary: 'FIRE' },
    38: { primary: 'FIRE' },
    39: { primary: 'NORMAL' },
    40: { primary: 'NORMAL' },
    41: { primary: 'POISON', secondary: 'FLYING' },
    42: { primary: 'POISON', secondary: 'FLYING' },
    43: { primary: 'GRASS', secondary: 'POISON' },
    44: { primary: 'GRASS', secondary: 'POISON' },
    45: { primary: 'GRASS', secondary: 'POISON' },
    46: { primary: 'BUG', secondary: 'GRASS' },
    47: { primary: 'BUG', secondary: 'GRASS' },
    48: { primary: 'BUG', secondary: 'POISON' },
    49: { primary: 'BUG', secondary: 'POISON' },
    50: { primary: 'GROUND' },
    51: { primary: 'GROUND' },
    52: { primary: 'NORMAL' },
    53: { primary: 'NORMAL' },
    54: { primary: 'WATER' },
    55: { primary: 'WATER' },
    56: { primary: 'FIGHTING' },
    57: { primary: 'FIGHTING' },
    58: { primary: 'FIRE' },
    59: { primary: 'FIRE' },
    60: { primary: 'WATER' },
    61: { primary: 'WATER' },
    62: { primary: 'WATER', secondary: 'FIGHTING' },
    63: { primary: 'PSYCHIC' },
    64: { primary: 'PSYCHIC' },
    65: { primary: 'PSYCHIC' },
    66: { primary: 'FIGHTING' },
    67: { primary: 'FIGHTING' },
    68: { primary: 'FIGHTING' },
    69: { primary: 'GRASS', secondary: 'POISON' },
    70: { primary: 'GRASS', secondary: 'POISON' },
    71: { primary: 'GRASS', secondary: 'POISON' },
    72: { primary: 'WATER', secondary: 'POISON' },
    73: { primary: 'WATER', secondary: 'POISON' },
    74: { primary: 'ROCK', secondary: 'GROUND' },
    75: { primary: 'ROCK', secondary: 'GROUND' },
    76: { primary: 'ROCK', secondary: 'GROUND' },
    77: { primary: 'FIRE' },
    78: { primary: 'FIRE' },
    79: { primary: 'WATER', secondary: 'PSYCHIC' },
    80: { primary: 'WATER', secondary: 'PSYCHIC' },
    81: { primary: 'ELECTRIC', secondary: 'STEEL' },
    82: { primary: 'ELECTRIC', secondary: 'STEEL' },
    83: { primary: 'NORMAL', secondary: 'FLYING' },
    84: { primary: 'NORMAL', secondary: 'FLYING' },
    85: { primary: 'NORMAL', secondary: 'FLYING' },
    86: { primary: 'WATER' },
    87: { primary: 'WATER', secondary: 'ICE' },
    88: { primary: 'POISON' },
    89: { primary: 'POISON' },
    90: { primary: 'WATER' },
    91: { primary: 'WATER', secondary: 'ICE' },
    92: { primary: 'GHOST', secondary: 'POISON' },
    93: { primary: 'GHOST', secondary: 'POISON' },
    94: { primary: 'GHOST', secondary: 'POISON' },
    95: { primary: 'ROCK', secondary: 'GROUND' },
    96: { primary: 'PSYCHIC' },
    97: { primary: 'PSYCHIC' },
    98: { primary: 'WATER' },
    99: { primary: 'WATER' },
    100: { primary: 'ELECTRIC' },
    101: { primary: 'ELECTRIC' },
    102: { primary: 'GRASS', secondary: 'PSYCHIC' },
    103: { primary: 'GRASS', secondary: 'PSYCHIC' },
    104: { primary: 'GROUND' },
    105: { primary: 'GROUND' },
    106: { primary: 'FIGHTING' },
    107: { primary: 'FIGHTING' },
    108: { primary: 'NORMAL' },
    109: { primary: 'POISON' },
    110: { primary: 'POISON' },
    111: { primary: 'GROUND', secondary: 'ROCK' },
    112: { primary: 'GROUND', secondary: 'ROCK' },
    113: { primary: 'NORMAL' },
    114: { primary: 'GRASS' },
    115: { primary: 'NORMAL' },
    116: { primary: 'WATER' },
    117: { primary: 'WATER' },
    118: { primary: 'WATER' },
    119: { primary: 'WATER' },
    120: { primary: 'WATER' },
    121: { primary: 'WATER', secondary: 'PSYCHIC' },
    122: { primary: 'PSYCHIC' },
    123: { primary: 'BUG', secondary: 'FLYING' },
    124: { primary: 'ICE', secondary: 'PSYCHIC' },
    125: { primary: 'ELECTRIC' },
    126: { primary: 'FIRE' },
    127: { primary: 'BUG' },
    128: { primary: 'NORMAL' },
    129: { primary: 'WATER' },
    130: { primary: 'WATER', secondary: 'FLYING' },
    131: { primary: 'WATER', secondary: 'ICE' },
    132: { primary: 'NORMAL' },
    133: { primary: 'NORMAL' },
    134: { primary: 'WATER' },
    135: { primary: 'ELECTRIC' },
    136: { primary: 'FIRE' },
    137: { primary: 'NORMAL' },
    138: { primary: 'ROCK', secondary: 'WATER' },
    139: { primary: 'ROCK', secondary: 'WATER' },
    140: { primary: 'ROCK', secondary: 'WATER' },
    141: { primary: 'ROCK', secondary: 'WATER' },
    142: { primary: 'ROCK', secondary: 'FLYING' },
    143: { primary: 'NORMAL' },
    144: { primary: 'ICE', secondary: 'FLYING' },
    145: { primary: 'ELECTRIC', secondary: 'FLYING' },
    146: { primary: 'FIRE', secondary: 'FLYING' },
    147: { primary: 'DRAGON' },
    148: { primary: 'DRAGON' },
    149: { primary: 'DRAGON', secondary: 'FLYING' },
    150: { primary: 'PSYCHIC' },
    151: { primary: 'PSYCHIC' },
    // Gen 2 & 3 Key starters & icons
    152: { primary: 'GRASS' },
    155: { primary: 'FIRE' },
    158: { primary: 'WATER' },
    249: { primary: 'PSYCHIC', secondary: 'FLYING' },
    250: { primary: 'FIRE', secondary: 'FLYING' },
    251: { primary: 'PSYCHIC', secondary: 'GRASS' },
    252: { primary: 'GRASS' },
    255: { primary: 'FIRE' },
    258: { primary: 'WATER' },
    280: { primary: 'PSYCHIC' },
    281: { primary: 'PSYCHIC' },
    282: { primary: 'PSYCHIC' },
    382: { primary: 'WATER' },
    383: { primary: 'GROUND' },
    384: { primary: 'DRAGON', secondary: 'FLYING' },
};

export function getPokemonTypes(speciesId: number): PokemonTypeInfo {
    const nationalId = getNationalDexId(speciesId);
    return SPECIES_TYPES[nationalId] || { primary: 'NORMAL' };
}

export const TYPE_BADGE_STYLES: Record<string, { bg: string; text: string; border: string }> = {
    NORMAL: { bg: '#A8A878', text: '#FFFFFF', border: '#6D6D4E' },
    FIRE: { bg: '#F08030', text: '#FFFFFF', border: '#9C531F' },
    WATER: { bg: '#6890F0', text: '#FFFFFF', border: '#445E9C' },
    GRASS: { bg: '#78C850', text: '#FFFFFF', border: '#4E8234' },
    ELECTRIC: { bg: '#F8D030', text: '#3A3000', border: '#A1871F' },
    ICE: { bg: '#98D8D8', text: '#1A3535', border: '#638D8D' },
    FIGHTING: { bg: '#C03028', text: '#FFFFFF', border: '#7D1F1A' },
    POISON: { bg: '#A040A0', text: '#FFFFFF', border: '#682A68' },
    GROUND: { bg: '#E0C068', text: '#3E341A', border: '#927D44' },
    FLYING: { bg: '#A890F0', text: '#FFFFFF', border: '#6D5E9C' },
    PSYCHIC: { bg: '#F85888', text: '#FFFFFF', border: '#A13959' },
    BUG: { bg: '#A8B820', text: '#FFFFFF', border: '#6D7815' },
    ROCK: { bg: '#B8A038', text: '#FFFFFF', border: '#786824' },
    GHOST: { bg: '#705898', text: '#FFFFFF', border: '#493963' },
    DRAGON: { bg: '#7038F8', text: '#FFFFFF', border: '#4924A1' },
    STEEL: { bg: '#B8B8D0', text: '#262630', border: '#787887' },
    DARK: { bg: '#705848', text: '#FFFFFF', border: '#49392F' },
    FAIRY: { bg: '#EE99AC', text: '#3E1E26', border: '#9B6470' },
};
